// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package userpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreateUserReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserRes struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRes) Reset()         { *m = CreateUserRes{} }
func (m *CreateUserRes) String() string { return proto.CompactTextString(m) }
func (*CreateUserRes) ProtoMessage()    {}
func (*CreateUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRes.Unmarshal(m, b)
}
func (m *CreateUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRes.Marshal(b, m, deterministic)
}
func (m *CreateUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRes.Merge(m, src)
}
func (m *CreateUserRes) XXX_Size() int {
	return xxx_messageInfo_CreateUserRes.Size(m)
}
func (m *CreateUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRes proto.InternalMessageInfo

func (m *CreateUserRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserReq) Reset()         { *m = UpdateUserReq{} }
func (m *UpdateUserReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserReq) ProtoMessage()    {}
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UpdateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserReq.Unmarshal(m, b)
}
func (m *UpdateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserReq.Merge(m, src)
}
func (m *UpdateUserReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserReq.Size(m)
}
func (m *UpdateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserReq proto.InternalMessageInfo

func (m *UpdateUserReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRes struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRes) Reset()         { *m = UpdateUserRes{} }
func (m *UpdateUserRes) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRes) ProtoMessage()    {}
func (*UpdateUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UpdateUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRes.Unmarshal(m, b)
}
func (m *UpdateUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRes.Marshal(b, m, deterministic)
}
func (m *UpdateUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRes.Merge(m, src)
}
func (m *UpdateUserRes) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRes.Size(m)
}
func (m *UpdateUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRes proto.InternalMessageInfo

func (m *UpdateUserRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ReadUserReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserReq) Reset()         { *m = ReadUserReq{} }
func (m *ReadUserReq) String() string { return proto.CompactTextString(m) }
func (*ReadUserReq) ProtoMessage()    {}
func (*ReadUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *ReadUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserReq.Unmarshal(m, b)
}
func (m *ReadUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserReq.Marshal(b, m, deterministic)
}
func (m *ReadUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserReq.Merge(m, src)
}
func (m *ReadUserReq) XXX_Size() int {
	return xxx_messageInfo_ReadUserReq.Size(m)
}
func (m *ReadUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserReq proto.InternalMessageInfo

func (m *ReadUserReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadUserRes struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserRes) Reset()         { *m = ReadUserRes{} }
func (m *ReadUserRes) String() string { return proto.CompactTextString(m) }
func (*ReadUserRes) ProtoMessage()    {}
func (*ReadUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *ReadUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRes.Unmarshal(m, b)
}
func (m *ReadUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRes.Marshal(b, m, deterministic)
}
func (m *ReadUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRes.Merge(m, src)
}
func (m *ReadUserRes) XXX_Size() int {
	return xxx_messageInfo_ReadUserRes.Size(m)
}
func (m *ReadUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRes proto.InternalMessageInfo

func (m *ReadUserRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserReq) Reset()         { *m = DeleteUserReq{} }
func (m *DeleteUserReq) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReq) ProtoMessage()    {}
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *DeleteUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReq.Unmarshal(m, b)
}
func (m *DeleteUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReq.Marshal(b, m, deterministic)
}
func (m *DeleteUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReq.Merge(m, src)
}
func (m *DeleteUserReq) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReq.Size(m)
}
func (m *DeleteUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReq proto.InternalMessageInfo

func (m *DeleteUserReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserRes struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRes) Reset()         { *m = DeleteUserRes{} }
func (m *DeleteUserRes) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRes) ProtoMessage()    {}
func (*DeleteUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *DeleteUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRes.Unmarshal(m, b)
}
func (m *DeleteUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRes.Marshal(b, m, deterministic)
}
func (m *DeleteUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRes.Merge(m, src)
}
func (m *DeleteUserRes) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRes.Size(m)
}
func (m *DeleteUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRes proto.InternalMessageInfo

func (m *DeleteUserRes) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*CreateUserReq)(nil), "user.CreateUserReq")
	proto.RegisterType((*CreateUserRes)(nil), "user.CreateUserRes")
	proto.RegisterType((*UpdateUserReq)(nil), "user.UpdateUserReq")
	proto.RegisterType((*UpdateUserRes)(nil), "user.UpdateUserRes")
	proto.RegisterType((*ReadUserReq)(nil), "user.ReadUserReq")
	proto.RegisterType((*ReadUserRes)(nil), "user.ReadUserRes")
	proto.RegisterType((*DeleteUserReq)(nil), "user.DeleteUserReq")
	proto.RegisterType((*DeleteUserRes)(nil), "user.DeleteUserRes")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4e, 0xb3, 0x50,
	0x10, 0xc5, 0x03, 0x1f, 0x1f, 0x81, 0x69, 0x6a, 0xe2, 0xb8, 0x21, 0x34, 0x55, 0xc3, 0xca, 0x85,
	0x62, 0x82, 0x6f, 0xa0, 0x5d, 0xbb, 0xc0, 0x74, 0xe3, 0xa6, 0xb9, 0x2d, 0x63, 0x42, 0x42, 0x05,
	0xef, 0xd0, 0xf8, 0x38, 0xbe, 0x94, 0x0f, 0x64, 0xee, 0xdc, 0x10, 0x01, 0x49, 0xaa, 0xbb, 0xdb,
	0xdf, 0x99, 0x33, 0x7f, 0x4e, 0x01, 0x38, 0x30, 0xe9, 0xb4, 0xd1, 0x75, 0x5b, 0xa3, 0x67, 0xde,
	0xc9, 0x87, 0x03, 0xde, 0x9a, 0x49, 0xe3, 0x09, 0xb8, 0x65, 0x11, 0x39, 0x97, 0xce, 0x55, 0x98,
	0xbb, 0x65, 0x81, 0x0b, 0x08, 0x4d, 0xc1, 0xe6, 0x55, 0xed, 0x29, 0x72, 0x05, 0x07, 0x06, 0x3c,
	0xaa, 0x3d, 0x61, 0x0c, 0x41, 0xa3, 0x98, 0xdf, 0x6b, 0x5d, 0x44, 0xff, 0xac, 0xd6, 0xfd, 0xc6,
	0x25, 0xc0, 0x4b, 0xa9, 0xb9, 0xb5, 0x4e, 0x4f, 0xd4, 0x50, 0x88, 0x58, 0x17, 0x10, 0x56, 0xaa,
	0x53, 0xff, 0x5b, 0xaf, 0x01, 0x22, 0x22, 0x78, 0xba, 0xae, 0x28, 0xf2, 0x85, 0xcb, 0x3b, 0xb9,
	0x85, 0xf9, 0x83, 0x26, 0xd5, 0x92, 0x59, 0x33, 0xa7, 0x37, 0x3c, 0x07, 0x59, 0x5d, 0x76, 0x9d,
	0x65, 0x90, 0xca, 0x4d, 0x22, 0xda, 0x93, 0x46, 0x06, 0xfe, 0x8d, 0x61, 0xdd, 0x14, 0x7f, 0x9b,
	0xd0, 0x37, 0x1c, 0x9f, 0xb0, 0x84, 0x59, 0x4e, 0xaa, 0xe8, 0xfa, 0x8f, 0xb2, 0x4e, 0x6e, 0xfa,
	0xf2, 0xf1, 0x6e, 0x17, 0x30, 0x5f, 0x51, 0x45, 0xdf, 0xfb, 0x8e, 0xfb, 0xa5, 0xc3, 0x02, 0x36,
	0xff, 0x49, 0xc9, 0x1b, 0x3e, 0xec, 0x76, 0xc4, 0x2c, 0x85, 0x41, 0x1e, 0x96, 0xfc, 0x64, 0x41,
	0xf6, 0xe9, 0x40, 0x60, 0x4a, 0x57, 0xaa, 0x55, 0x98, 0x81, 0x6f, 0xe3, 0xc3, 0x33, 0x3b, 0x79,
	0x90, 0x7e, 0x3c, 0x01, 0x19, 0xaf, 0xc1, 0x33, 0x07, 0xe0, 0xa9, 0x15, 0x7b, 0xb7, 0xc6, 0x3f,
	0x10, 0x9b, 0x09, 0x36, 0xbe, 0x6e, 0xc2, 0x20, 0xfd, 0x78, 0x02, 0x8a, 0xc7, 0x9e, 0xd4, 0x79,
	0x06, 0x09, 0xc4, 0x13, 0x90, 0xef, 0x83, 0x67, 0xdf, 0xd0, 0x66, 0xbb, 0xf5, 0xe5, 0x93, 0xbf,
	0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x65, 0xf5, 0xd1, 0xca, 0x00, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserDataClient is the client API for UserData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserDataClient interface {
	Create(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserRes, error)
	Read(ctx context.Context, in *ReadUserReq, opts ...grpc.CallOption) (*ReadUserRes, error)
	Update(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error)
	Delete(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRes, error)
}

type userDataClient struct {
	cc *grpc.ClientConn
}

func NewUserDataClient(cc *grpc.ClientConn) UserDataClient {
	return &userDataClient{cc}
}

func (c *userDataClient) Create(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserRes, error) {
	out := new(CreateUserRes)
	err := c.cc.Invoke(ctx, "/user.UserData/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDataClient) Read(ctx context.Context, in *ReadUserReq, opts ...grpc.CallOption) (*ReadUserRes, error) {
	out := new(ReadUserRes)
	err := c.cc.Invoke(ctx, "/user.UserData/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDataClient) Update(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error) {
	out := new(UpdateUserRes)
	err := c.cc.Invoke(ctx, "/user.UserData/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDataClient) Delete(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRes, error) {
	out := new(DeleteUserRes)
	err := c.cc.Invoke(ctx, "/user.UserData/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDataServer is the server API for UserData service.
type UserDataServer interface {
	Create(context.Context, *CreateUserReq) (*CreateUserRes, error)
	Read(context.Context, *ReadUserReq) (*ReadUserRes, error)
	Update(context.Context, *UpdateUserReq) (*UpdateUserRes, error)
	Delete(context.Context, *DeleteUserReq) (*DeleteUserRes, error)
}

// UnimplementedUserDataServer can be embedded to have forward compatible implementations.
type UnimplementedUserDataServer struct {
}

func (*UnimplementedUserDataServer) Create(ctx context.Context, req *CreateUserReq) (*CreateUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserDataServer) Read(ctx context.Context, req *ReadUserReq) (*ReadUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedUserDataServer) Update(ctx context.Context, req *UpdateUserReq) (*UpdateUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUserDataServer) Delete(ctx context.Context, req *DeleteUserReq) (*DeleteUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterUserDataServer(s *grpc.Server, srv UserDataServer) {
	s.RegisterService(&_UserData_serviceDesc, srv)
}

func _UserData_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDataServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserData/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDataServer).Create(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserData_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDataServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserData/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDataServer).Read(ctx, req.(*ReadUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserData_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDataServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserData/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDataServer).Update(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserData_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDataServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserData/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDataServer).Delete(ctx, req.(*DeleteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserData",
	HandlerType: (*UserDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserData_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _UserData_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserData_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserData_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
