version: '3'
services:
  app:
    build: web-app
    restart: always
    tty: true
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo/data:/data/db
      - ./db/mongo/configdb:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - ./.env
    ports:
      - 8081:8081

