[sofalib]
api_key = "XXXXXXXXXXXXX"
api_secret = "XXXXXXXXXXXXXXXXXXXXXXXX"

[logging]
log_file = "go-3daudio.log"

[db]
# use .env to hide username and password from the outside
# name = root:root@tcp(127.0.0.1:33060)/go3daudio?parseTime=true
# name = root:root@tcp(db:3306)/go3daudio?parseTime=true
#name = "%s:%s@tcp(go-3daudio.czgopozochto.ap-northeast-1.rds.amazonaws.com:3306)/go3daudio?parseTime=true"
# name = hrtf_data.sql
# driver = sqlite3

driver = "mysql"

#host = "go-3daudio.czgopozochto.ap-northeast-1.rds.amazonaws.com"
host = "db"
port = 27017
name = "go3daudio"
#etc = "?parseTime=true"
etc = ""

[web]
port = 80
